name: Build and Release Executables

on:
  push:
    tags:
      - 'v*'  # O workflow será executado quando você criar uma tag, como v1.0.0

jobs:
  build-linux:
    runs-on: ubuntu-latest  # Job específico para Linux
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Defina a versão do Python que seu projeto utiliza

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executable for Linux
        run: |
          pyinstaller --onefile --distpath=dist/linux --workpath=build/linux main.py

      - name: Upload Linux release assets
        uses: softprops/action-gh-release@v1
        with:
          files: dist/linux/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest  # Job específico para Windows
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Defina a versão do Python que seu projeto utiliza

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executable for Windows
        run: |
          pyinstaller --onefile --distpath=dist/windows --workpath=build/windows main.py

      - name: Upload Windows release assets
        uses: softprops/action-gh-release@v1
        with:
          files: dist/windows/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
